### ISSUE TITLE
Various annoying things with the usage instructions

### ISSUE THREAD

**Issue by KenGordon** [microsoft/confidential-sidecar-containers#11]
Need to be clear that the generatefs.sh needs to run in a wsl or linux
Be clear it is not a 5 minute job.
mHSM and blob storage account/container prerequisites.
List of apt installs - eg cryptsetup, cl-base64, go etc etc as per Saket's session
Be very clear about the ordering and the dependencies between the various json config files.
Fix the azcopy line to use az storage blob upload to avoid an extra install
az storage blob upload --file generatefs/encfs.img --container-name kengordo-encfs-container --name KenBlob --account-name kegordoencfs --sas-token 'My-SAS-Token-Of-The-Day-note-the-quotes-because-of-%-etc'
Generally less reliance on the links to other docs which are of course much more general.
Fix the base importkeyconfig.json and encfs-sidecar-args.json to use an OCT key (default) and clear out the key derivation stuff.
Screen shots.
Anything else...

**Comment by BryceDFisher** [comment]
Usage instructions have been overhauled.  Please open a new ticket with suggestions if the new instructions are still lacking.
